// ═══════════════════════════════════════════════════════════════════════════════
// BIBLIOTECA CIENTÍFICA DE EJERCICIOS — JUD PERFORMANCE
// ═══════════════════════════════════════════════════════════════════════════════

export const GRUPOS = [
  { id:"pecho", nombre:"Pecho", emoji:"💪", color:"#FF6B35", imagen:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Pectoralis_major.png/220px-Pectoralis_major.png" },
  { id:"espalda", nombre:"Espalda", emoji:"🦾", color:"#4A9EFF", imagen:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Latissimus_dorsi.png/220px-Latissimus_dorsi.png" },
  { id:"hombros", nombre:"Hombros", emoji:"🔱", color:"#8B5CF6", imagen:"" },
  { id:"biceps", nombre:"Bíceps", emoji:"💪", color:"#FF4757", imagen:"" },
  { id:"triceps", nombre:"Tríceps", emoji:"💥", color:"#FF6B35", imagen:"" },
  { id:"piernas", nombre:"Piernas", emoji:"🦵", color:"#2ECC8E", imagen:"" },
  { id:"gluteos", nombre:"Glúteos", emoji:"🍑", color:"#FFD32A", imagen:"" },
  { id:"core", nombre:"Core / Abdomen", emoji:"⚡", color:"#4A9EFF", imagen:"" },
  { id:"cardio", nombre:"Cardio", emoji:"❤️", color:"#FF4757", imagen:"" },
];

export const METODOS = [
  { id:"estandar", nombre:"Series estándar", descripcion:"Series con el mismo peso y repeticiones", icono:"📊", color:"#4A9EFF" },
  { id:"piramide_asc", nombre:"Pirámide ascendente", descripcion:"Aumentar peso y reducir reps cada serie", icono:"📈", color:"#FF6B35" },
  { id:"piramide_desc", nombre:"Pirámide descendente", descripcion:"Empezar pesado e ir bajando el peso", icono:"📉", color:"#8B5CF6" },
  { id:"piramide_doble", nombre:"Pirámide doble", descripcion:"Subir y luego bajar el peso (diamante)", icono:"💎", color:"#FFD32A" },
  { id:"rest_pause", nombre:"Rest-Pause", descripcion:"Pausa corta (10-15s) dentro de la serie para continuar", icono:"⏸️", color:"#2ECC8E" },
  { id:"drop_set", nombre:"Drop Set", descripcion:"Reducir peso sin descanso hasta el fallo", icono:"⬇️", color:"#FF4757" },
  { id:"superset", nombre:"Superset", descripcion:"Dos ejercicios consecutivos sin descanso", icono:"🔄", color:"#4A9EFF" },
  { id:"triset", nombre:"Triset", descripcion:"Tres ejercicios consecutivos sin descanso", icono:"🔁", color:"#8B5CF6" },
  { id:"giant_set", nombre:"Giant Set", descripcion:"4+ ejercicios consecutivos sin descanso", icono:"💥", color:"#FF6B35" },
  { id:"pre_fatiga", nombre:"Pre-fatiga", descripcion:"Ejercicio de aislamiento antes del compuesto", icono:"🎯", color:"#FFD32A" },
  { id:"post_fatiga", nombre:"Post-fatiga", descripcion:"Ejercicio de aislamiento después del compuesto", icono:"🎯", color:"#2ECC8E" },
  { id:"tempo", nombre:"Tempo Training", descripcion:"Control del tiempo en cada fase del movimiento", icono:"⏱️", color:"#4A9EFF" },
  { id:"mecanico", nombre:"Series mecánicas", descripcion:"Cambiar ángulo/posición para continuar la serie", icono:"🔧", color:"#FF4757" },
  { id:"cluster", nombre:"Cluster Sets", descripcion:"Mini-descansos dentro de la serie (10-20s)", icono:"🧩", color:"#8B5CF6" },
];

export const EJERCICIOS = [
  // ─── PECHO ────────────────────────────────────────────────────────────────
  { id:"p1", video:"https://www.youtube.com/watch?v=4Y2ZdHCOXok", nombre:"Press de Banca con Barra", grupo:"pecho", equipo:"Barra libre", tipo:"Compuesto", dificultad:"Intermedio", principal:"Pectoral mayor", secundarios:["Deltoides anterior","Tríceps"], series:"3-5", reps:"4-10", descanso:"120-180s", rir:"2-3", rpe:"7-8", notas:"Codos a 75°, escápulas retraídas. El ejercicio más validado para hipertrofia pectoral.", alternativas:["p4","p7","p10"] },
  { id:"p2", video:"https://www.youtube.com/watch?v=DbFgADa2PL8", nombre:"Press Inclinado con Barra", grupo:"pecho", equipo:"Barra libre", tipo:"Compuesto", dificultad:"Intermedio", principal:"Pectoral clavicular", secundarios:["Deltoides anterior","Tríceps"], series:"3-4", reps:"6-12", descanso:"90-120s", rir:"2-3", rpe:"7-8", notas:"Inclinación 30-45°. Mayor activación porción clavicular.", alternativas:["p5","p8","p11"] },
  { id:"p3", video:"https://www.youtube.com/watch?v=OR6TFCqcKp4", nombre:"Press Declinado con Barra", grupo:"pecho", equipo:"Barra libre", tipo:"Compuesto", dificultad:"Intermedio", principal:"Pectoral esternal inferior", secundarios:["Tríceps"], series:"3-4", reps:"8-12", descanso:"90s", rir:"2-3", rpe:"7", notas:"Declive 15-30°. Activa la porción inferior del pectoral.", alternativas:["p6","p9"] },
  { id:"p4", video:"https://www.youtube.com/watch?v=QsYre__-aro", nombre:"Press con Mancuernas Plano", grupo:"pecho", equipo:"Mancuernas", tipo:"Compuesto", dificultad:"Principiante", principal:"Pectoral mayor", secundarios:["Deltoides anterior","Tríceps"], series:"3-4", reps:"8-15", descanso:"90s", rir:"2-3", rpe:"7", notas:"Mayor ROM que barra. Permite rotación neutra.", alternativas:["p1","p7","p10"] },
  { id:"p5", video:"https://www.youtube.com/watch?v=8iPEnn-ltC8", nombre:"Press Inclinado con Mancuernas", grupo:"pecho", equipo:"Mancuernas", tipo:"Compuesto", dificultad:"Principiante", principal:"Pectoral clavicular", secundarios:["Deltoides anterior"], series:"3-4", reps:"10-15", descanso:"90s", rir:"2-3", rpe:"7", notas:"30-45° inclinación. Ideal para pecho superior.", alternativas:["p2","p8","p11"] },
  { id:"p6", video:"https://www.youtube.com/watch?v=LfyQmbS6FAQ", nombre:"Press Declinado con Mancuernas", grupo:"pecho", equipo:"Mancuernas", tipo:"Compuesto", dificultad:"Principiante", principal:"Pectoral esternal", secundarios:["Tríceps"], series:"3-4", reps:"10-15", descanso:"90s", rir:"2-3", rpe:"7", notas:"Mayor estabilización. Buen rango de movimiento.", alternativas:["p3","p9"] },
  { id:"p7", video:"https://www.youtube.com/watch?v=eozdVDA78K0", nombre:"Aperturas con Mancuernas Plano", grupo:"pecho", equipo:"Mancuernas", tipo:"Aislamiento", dificultad:"Principiante", principal:"Pectoral mayor", secundarios:["Deltoides anterior"], series:"3-4", reps:"10-15", descanso:"60-90s", rir:"1-2", rpe:"7", notas:"Codos ligeramente flexionados. Estiramiento máximo en el fondo.", alternativas:["p10","p13"] },
  { id:"p8", video:"https://www.youtube.com/watch?v=OmBkaIoYHH8", nombre:"Aperturas Inclinadas con Mancuernas", grupo:"pecho", equipo:"Mancuernas", tipo:"Aislamiento", dificultad:"Principiante", principal:"Pectoral clavicular", secundarios:[], series:"3", reps:"12-15", descanso:"60s", rir:"1-2", rpe:"7", notas:"Excelente para tensión en el pecho superior.", alternativas:["p11","p14"] },
  { id:"p9", video:"https://www.youtube.com/watch?v=6kALZikXxLc", nombre:"Fondos en Paralelas (Pecho)", grupo:"pecho", equipo:"Peso corporal", tipo:"Compuesto", dificultad:"Intermedio", principal:"Pectoral mayor inferior", secundarios:["Tríceps","Deltoides anterior"], series:"3-4", reps:"8-15", descanso:"90s", rir:"2-3", rpe:"8", notas:"Inclinar torso 30° adelante para enfoque pectoral.", alternativas:["p3","p6"] },
  { id:"p10", video:"https://www.youtube.com/watch?v=taI4XduLpTk", nombre:"Cable Crossover", grupo:"pecho", equipo:"Cable", tipo:"Aislamiento", dificultad:"Principiante", principal:"Pectoral mayor", secundarios:["Deltoides anterior"], series:"3-4", reps:"12-20", descanso:"60s", rir:"1-2", rpe:"7", notas:"Tensión constante en todo el rango. Ideal para definición.", alternativas:["p7","p13"] },
  { id:"p11", video:"https://www.youtube.com/watch?v=kokahylZeB0", nombre:"Cable Crossover Alto (Pecho inferior)", grupo:"pecho", equipo:"Cable", tipo:"Aislamiento", dificultad:"Principiante", principal:"Pectoral inferior", secundarios:[], series:"3", reps:"15-20", descanso:"60s", rir:"1-2", rpe:"7", notas:"Poleas altas, manos cruzan hacia abajo.", alternativas:["p8","p9"] },
  { id:"p12", video:"https://www.youtube.com/watch?v=xUm0BiZCWlQ", nombre:"Press en Máquina Pecho", grupo:"pecho", equipo:"Máquina", tipo:"Compuesto", dificultad:"Principiante", principal:"Pectoral mayor", secundarios:["Tríceps"], series:"3-4", reps:"10-15", descanso:"90s", rir:"2-3", rpe:"7", notas:"Ideal para principiantes o como ejercicio finalizador.", alternativas:["p1","p4"] },
  { id:"p13", video:"https://www.youtube.com/watch?v=Z57CtFmRMxA", nombre:"Pec Deck / Mariposa", grupo:"pecho", equipo:"Máquina", tipo:"Aislamiento", dificultad:"Principiante", principal:"Pectoral mayor", secundarios:[], series:"3-4", reps:"12-20", descanso:"60s", rir:"1-2", rpe:"7", notas:"Tensión constante. Excelente para conexión mente-músculo.", alternativas:["p7","p10"] },
  { id:"p14", video:"https://www.youtube.com/watch?v=IODxDxX7oi4", nombre:"Push-up", grupo:"pecho", equipo:"Peso corporal", tipo:"Compuesto", dificultad:"Principiante", principal:"Pectoral mayor", secundarios:["Tríceps","Core"], series:"3-4", reps:"10-20", descanso:"60s", rir:"2-3", rpe:"7", notas:"Progresivo: piernas elevadas para mayor dificultad.", alternativas:["p4","p9"] },

  // ─── ESPALDA ──────────────────────────────────────────────────────────────
  { id:"e1", video:"https://www.youtube.com/watch?v=eGo4IYlbE5g", nombre:"Dominadas con Peso", grupo:"espalda", equipo:"Barra fija", tipo:"Compuesto", dificultad:"Avanzado", principal:"Dorsal ancho", secundarios:["Bíceps","Romboides","Trapecio medio"], series:"3-5", reps:"4-10", descanso:"120-180s", rir:"2-3", rpe:"8-9", notas:"Agarre prono, escápulas hacia abajo y atrás. El mejor ejercicio para ancho de espalda.", alternativas:["e4","e7"] },
  { id:"e2", video:"https://www.youtube.com/watch?v=T3N-TO4reLQ", nombre:"Remo con Barra", grupo:"espalda", equipo:"Barra libre", tipo:"Compuesto", dificultad:"Intermedio", principal:"Dorsal ancho", secundarios:["Romboides","Trapecio medio","Bíceps"], series:"3-5", reps:"5-10", descanso:"120-180s", rir:"2-3", rpe:"8", notas:"Torso a 45-70°, barra a abdomen. El mejor para grosor de espalda.", alternativas:["e5","e8","e11"] },
  { id:"e3", video:"https://www.youtube.com/watch?v=op9kVnSso6Q", nombre:"Peso Muerto Convencional", grupo:"espalda", equipo:"Barra libre", tipo:"Compuesto", dificultad:"Avanzado", principal:"Erector espinal", secundarios:["Glúteos","Isquiotibiales","Trapecio","Dorsales"], series:"3-5", reps:"3-8", descanso:"180-300s", rir:"2-3", rpe:"8-9", notas:"El ejercicio más completo. Espalda neutra, caderas bisagra. Alta activación del SNC.", alternativas:["e9","e10"] },
  { id:"e4", video:"https://www.youtube.com/watch?v=CAwf7n6Luuc", nombre:"Jalón al Pecho", grupo:"espalda", equipo:"Cable", tipo:"Compuesto", dificultad:"Principiante", principal:"Dorsal ancho", secundarios:["Bíceps","Romboides"], series:"3-4", reps:"8-15", descanso:"90s", rir:"2-3", rpe:"7", notas:"Agarre prono ancho. Llevar barra a clavícula.", alternativas:["e1","e7"] },
  { id:"e5", video:"https://www.youtube.com/watch?v=pYcpY20QaE8", nombre:"Remo con Mancuerna", grupo:"espalda", equipo:"Mancuernas", tipo:"Compuesto", dificultad:"Principiante", principal:"Dorsal ancho", secundarios:["Romboides","Bíceps"], series:"3-4", reps:"10-15", descanso:"90s", rir:"2-3", rpe:"7", notas:"Apoyar rodilla y mano en banco. Codo cerca del cuerpo.", alternativas:["e2","e8","e11"] },
  { id:"e6", video:"https://www.youtube.com/watch?v=GZbfZ033f74", nombre:"Remo en Máquina", grupo:"espalda", equipo:"Máquina", tipo:"Compuesto", dificultad:"Principiante", principal:"Dorsal ancho", secundarios:["Romboides","Bíceps"], series:"3-4", reps:"10-15", descanso:"90s", rir:"2-3", rpe:"7", notas:"Pecho apoyado. Ideal para principiantes.", alternativas:["e2","e5"] },
  { id:"e7", video:"https://www.youtube.com/watch?v=1bFHLpO6bkw", nombre:"Dominadas Australianas (Remo en barra)", grupo:"espalda", equipo:"Barra fija", tipo:"Compuesto", dificultad:"Principiante", principal:"Dorsal ancho", secundarios:["Bíceps","Romboides"], series:"3-4", reps:"10-20", descanso:"90s", rir:"2-3", rpe:"7", notas:"Progresión hacia dominadas completas.", alternativas:["e1","e4"] },
  { id:"e8", video:"https://www.youtube.com/watch?v=GZbfZ033f74", nombre:"Remo en Polea Baja", grupo:"espalda", equipo:"Cable", tipo:"Compuesto", dificultad:"Principiante", principal:"Dorsal ancho", secundarios:["Romboides","Bíceps"], series:"3-4", reps:"10-15", descanso:"90s", rir:"2-3", rpe:"7", notas:"Mantener torso estable. No balancear.", alternativas:["e2","e5","e11"] },
  { id:"e9", video:"https://www.youtube.com/watch?v=JCXUYuzwNrM", nombre:"Peso Muerto Rumano", grupo:"espalda", equipo:"Barra libre", tipo:"Compuesto", dificultad:"Intermedio", principal:"Erector espinal", secundarios:["Isquiotibiales","Glúteos"], series:"3-4", reps:"8-12", descanso:"120s", rir:"2-3", rpe:"7-8", notas:"Bisagra de cadera, rodillas ligeramente flexionadas. Espalda neutra.", alternativas:["e3","e10"] },
  { id:"e10", video:"https://www.youtube.com/watch?v=bPv_qnlNfXA", nombre:"Good Morning", grupo:"espalda", equipo:"Barra libre", tipo:"Compuesto", dificultad:"Avanzado", principal:"Erector espinal", secundarios:["Isquiotibiales","Glúteos"], series:"3-4", reps:"8-12", descanso:"120s", rir:"3", rpe:"7", notas:"Barra en trapecios, bisagra de cadera. Alta técnica requerida.", alternativas:["e3","e9"] },
  { id:"e11", video:"https://www.youtube.com/watch?v=hQNfqveoGEE", nombre:"Remo con Mancuernas Bilateral", grupo:"espalda", equipo:"Mancuernas", tipo:"Compuesto", dificultad:"Principiante", principal:"Romboides", secundarios:["Trapecio medio","Bíceps"], series:"3-4", reps:"10-15", descanso:"90s", rir:"2-3", rpe:"7", notas:"Torso inclinado, remo bilateral simultáneo.", alternativas:["e2","e5","e8"] },
  { id:"e12", video:"https://www.youtube.com/watch?v=FK4rHCWCDjY", nombre:"Pullover con Mancuerna", grupo:"espalda", equipo:"Mancuernas", tipo:"Aislamiento", dificultad:"Principiante", principal:"Dorsal ancho", secundarios:["Pectoral mayor","Serrato"], series:"3-4", reps:"12-15", descanso:"60-90s", rir:"2", rpe:"7", notas:"Arco de movimiento amplio. Excelente estiramiento del dorsal.", alternativas:["e4","e7"] },
  { id:"e13", video:"https://www.youtube.com/watch?v=qvIwWTfHDi4", nombre:"Face Pull", grupo:"espalda", equipo:"Cable", tipo:"Aislamiento", dificultad:"Principiante", principal:"Deltoides posterior", secundarios:["Romboides","Manguito rotador"], series:"3-4", reps:"15-20", descanso:"60s", rir:"1-2", rpe:"6-7", notas:"Cuerda a altura facial. Excelente para salud del manguito rotador.", alternativas:["e14"] },
  { id:"e14", video:"https://www.youtube.com/watch?v=NAqCVe2mwzM", nombre:"Encogimientos de Hombros (Shrugs)", grupo:"espalda", equipo:"Barra libre", tipo:"Aislamiento", dificultad:"Principiante", principal:"Trapecio superior", secundarios:[], series:"3-4", reps:"10-15", descanso:"60-90s", rir:"2-3", rpe:"7", notas:"Movimiento vertical puro. No rotar hombros.", alternativas:["e15"] },
  { id:"e15", video:"https://www.youtube.com/watch?v=Rr4ByIMnsuU", nombre:"Encogimientos con Mancuernas", grupo:"espalda", equipo:"Mancuernas", tipo:"Aislamiento", dificultad:"Principiante", principal:"Trapecio superior", secundarios:[], series:"3-4", reps:"12-15", descanso:"60s", rir:"2-3", rpe:"7", notas:"Mayor rango de movimiento que con barra.", alternativas:["e14"] },

  // ─── HOMBROS ──────────────────────────────────────────────────────────────
  { id:"h1", video:"https://www.youtube.com/watch?v=qEwKCR5JCog", nombre:"Press Militar con Barra (de pie)", grupo:"hombros", equipo:"Barra libre", tipo:"Compuesto", dificultad:"Intermedio", principal:"Deltoides anterior", secundarios:["Deltoides medio","Tríceps","Trapecio"], series:"3-5", reps:"5-10", descanso:"120-180s", rir:"2-3", rpe:"8", notas:"Barra desde el pecho hasta extensión completa. Gran activador del deltoides.", alternativas:["h2","h4","h7"] },
  { id:"h2", video:"https://www.youtube.com/watch?v=qEwKCR5JCog", nombre:"Press con Mancuernas Sentado", grupo:"hombros", equipo:"Mancuernas", tipo:"Compuesto", dificultad:"Principiante", principal:"Deltoides anterior y medio", secundarios:["Tríceps"], series:"3-4", reps:"8-15", descanso:"90s", rir:"2-3", rpe:"7", notas:"Mayor rango de movimiento. Permite rotación natural.", alternativas:["h1","h4","h7"] },
  { id:"h3", video:"https://www.youtube.com/watch?v=3VcKaXpzqRo", nombre:"Elevaciones Laterales con Mancuernas", grupo:"hombros", equipo:"Mancuernas", tipo:"Aislamiento", dificultad:"Principiante", principal:"Deltoides medio", secundarios:[], series:"3-5", reps:"12-20", descanso:"60s", rir:"1-2", rpe:"7", notas:"El único ejercicio que aísla el deltoides medio. Clave para anchura de hombros.", alternativas:["h8","h9"] },
  { id:"h4", video:"https://www.youtube.com/watch?v=6Z15_WdXmVw", nombre:"Press Arnold", grupo:"hombros", equipo:"Mancuernas", tipo:"Compuesto", dificultad:"Intermedio", principal:"Deltoides (3 porciones)", secundarios:["Tríceps"], series:"3-4", reps:"10-12", descanso:"90s", rir:"2-3", rpe:"7-8", notas:"Rotación interna a externa durante el press. Activa los 3 haces del deltoides.", alternativas:["h1","h2"] },
  { id:"h5", video:"https://www.youtube.com/watch?v=ttvfGg9d76c", nombre:"Pájaro / Elevación Posterior con Mancuernas", grupo:"hombros", equipo:"Mancuernas", tipo:"Aislamiento", dificultad:"Principiante", principal:"Deltoides posterior", secundarios:["Romboides","Trapecio medio"], series:"3-4", reps:"12-20", descanso:"60s", rir:"1-2", rpe:"7", notas:"Torso inclinado. Codos ligeramente flexionados.", alternativas:["h10","e13"] },
  { id:"h6", video:"https://www.youtube.com/watch?v=sOiBMsKDiUs", nombre:"Elevación Frontal con Barra", grupo:"hombros", equipo:"Barra libre", tipo:"Aislamiento", dificultad:"Principiante", principal:"Deltoides anterior", secundarios:[], series:"3", reps:"12-15", descanso:"60s", rir:"2", rpe:"7", notas:"Agarre prono, elevar hasta horizontal.", alternativas:["h11"] },
  { id:"h7", video:"https://www.youtube.com/watch?v=Wqq43dKW1TU", nombre:"Press en Máquina de Hombros", grupo:"hombros", equipo:"Máquina", tipo:"Compuesto", dificultad:"Principiante", principal:"Deltoides anterior y medio", secundarios:["Tríceps"], series:"3-4", reps:"10-15", descanso:"90s", rir:"2-3", rpe:"7", notas:"Ideal para principiantes o rehabilitación.", alternativas:["h1","h2"] },
  { id:"h8", video:"https://www.youtube.com/watch?v=gJY_CS9VVAM", nombre:"Elevaciones Laterales en Cable", grupo:"hombros", equipo:"Cable", tipo:"Aislamiento", dificultad:"Principiante", principal:"Deltoides medio", secundarios:[], series:"3-4", reps:"15-20", descanso:"60s", rir:"1-2", rpe:"7", notas:"Tensión constante a diferencia de mancuernas.", alternativas:["h3","h9"] },
  { id:"h9", video:"https://www.youtube.com/watch?v=gJY_CS9VVAM", nombre:"Elevaciones Laterales en Máquina", grupo:"hombros", equipo:"Máquina", tipo:"Aislamiento", dificultad:"Principiante", principal:"Deltoides medio", secundarios:[], series:"3-4", reps:"15-20", descanso:"60s", rir:"1-2", rpe:"7", notas:"Resistencia mecánica acomodante.", alternativas:["h3","h8"] },
  { id:"h10", video:"https://www.youtube.com/watch?v=ttvfGg9d76c", nombre:"Reverse Pec Deck (Mariposa invertida)", grupo:"hombros", equipo:"Máquina", tipo:"Aislamiento", dificultad:"Principiante", principal:"Deltoides posterior", secundarios:["Romboides"], series:"3-4", reps:"12-20", descanso:"60s", rir:"1-2", rpe:"7", notas:"Excelente para deltoides posterior. Esencial para equilibrio muscular.", alternativas:["h5","e13"] },
  { id:"h11", video:"https://www.youtube.com/watch?v=sOiBMsKDiUs", nombre:"Elevación Frontal con Mancuernas", grupo:"hombros", equipo:"Mancuernas", tipo:"Aislamiento", dificultad:"Principiante", principal:"Deltoides anterior", secundarios:[], series:"3", reps:"12-15", descanso:"60s", rir:"2", rpe:"7", notas:"Alternado o simultáneo. Control total del movimiento.", alternativas:["h6"] },

  // ─── BÍCEPS ───────────────────────────────────────────────────────────────
  { id:"b1", video:"https://www.youtube.com/watch?v=ykJmrZ5v0Oo", nombre:"Curl con Barra Recta", grupo:"biceps", equipo:"Barra libre", tipo:"Compuesto", dificultad:"Principiante", principal:"Bíceps braquial", secundarios:["Braquial","Braquiorradial"], series:"3-4", reps:"8-12", descanso:"90s", rir:"2-3", rpe:"7", notas:"El ejercicio más eficiente para bíceps. Codos fijos al costado del torso.", alternativas:["b2","b3","b7"] },
  { id:"b2", video:"https://www.youtube.com/watch?v=av7-8igSXTs", nombre:"Curl con Mancuernas", grupo:"biceps", equipo:"Mancuernas", tipo:"Compuesto", dificultad:"Principiante", principal:"Bíceps braquial", secundarios:["Braquial","Braquiorradial"], series:"3-4", reps:"10-15", descanso:"90s", rir:"2-3", rpe:"7", notas:"Supinación al subir. Permite trabajo unilateral.", alternativas:["b1","b3","b7"] },
  { id:"b3", video:"https://www.youtube.com/watch?v=zC3nLlEvin4", nombre:"Curl Martillo", grupo:"biceps", equipo:"Mancuernas", tipo:"Compuesto", dificultad:"Principiante", principal:"Braquiorradial", secundarios:["Bíceps","Braquial"], series:"3-4", reps:"10-15", descanso:"90s", rir:"2-3", rpe:"7", notas:"Agarre neutro. Excelente para el grosor del brazo.", alternativas:["b1","b2","b8"] },
  { id:"b4", video:"https://www.youtube.com/watch?v=Jvj2wV0vOYU", nombre:"Curl Concentrado", grupo:"biceps", equipo:"Mancuernas", tipo:"Aislamiento", dificultad:"Principiante", principal:"Bíceps braquial (pico)", secundarios:[], series:"3-4", reps:"12-15", descanso:"60s", rir:"1-2", rpe:"7", notas:"Codo apoyado en muslo. Máxima contracción y conexión mental.", alternativas:["b5","b6"] },
  { id:"b5", video:"https://www.youtube.com/watch?v=fIWP-FRFNU0", nombre:"Curl en Banco Predicador", grupo:"biceps", equipo:"Barra libre", tipo:"Aislamiento", dificultad:"Principiante", principal:"Bíceps braquial (cabeza corta)", secundarios:["Braquial"], series:"3-4", reps:"10-15", descanso:"60-90s", rir:"1-2", rpe:"7", notas:"Énfasis en la porción distal del bíceps. No hiperextender en el fondo.", alternativas:["b4","b6"] },
  { id:"b6", video:"https://www.youtube.com/watch?v=NFzTWp2qpiE", nombre:"Curl en Cable con Barra", grupo:"biceps", equipo:"Cable", tipo:"Aislamiento", dificultad:"Principiante", principal:"Bíceps braquial", secundarios:["Braquial"], series:"3-4", reps:"12-20", descanso:"60s", rir:"1-2", rpe:"7", notas:"Tensión constante. Ideal como finalizador.", alternativas:["b1","b5"] },
  { id:"b7", video:"https://www.youtube.com/watch?v=kwG2ipFRgfo", nombre:"Curl con Barra Z (EZ Bar)", grupo:"biceps", equipo:"Barra libre", tipo:"Compuesto", dificultad:"Principiante", principal:"Bíceps braquial", secundarios:["Braquiorradial"], series:"3-4", reps:"8-12", descanso:"90s", rir:"2-3", rpe:"7", notas:"Menor estrés en muñecas que la barra recta.", alternativas:["b1","b2"] },
  { id:"b8", video:"https://www.youtube.com/watch?v=nODnI3BzJo0", nombre:"Curl Inverso con Barra", grupo:"biceps", equipo:"Barra libre", tipo:"Compuesto", dificultad:"Principiante", principal:"Braquiorradial", secundarios:["Extensores del antebrazo"], series:"3", reps:"10-15", descanso:"60-90s", rir:"2-3", rpe:"7", notas:"Agarre supino inverso. Excelente para antebrazos y braquiorradial.", alternativas:["b3"] },

  // ─── TRÍCEPS ──────────────────────────────────────────────────────────────
  { id:"t1", video:"https://www.youtube.com/watch?v=d_KZxkY_0cM", nombre:"Press Francés con Barra", grupo:"triceps", equipo:"Barra libre", tipo:"Aislamiento", dificultad:"Intermedio", principal:"Tríceps (cabeza larga)", secundarios:[], series:"3-4", reps:"8-12", descanso:"90s", rir:"2-3", rpe:"7", notas:"Codos apuntando al techo. La cabeza larga se activa en extensión sobre la cabeza.", alternativas:["t2","t5"] },
  { id:"t2", video:"https://www.youtube.com/watch?v=d_KZxkY_0cM", nombre:"Press Francés con Mancuernas", grupo:"triceps", equipo:"Mancuernas", tipo:"Aislamiento", dificultad:"Principiante", principal:"Tríceps (cabeza larga)", secundarios:[], series:"3-4", reps:"10-15", descanso:"90s", rir:"2-3", rpe:"7", notas:"Unilateral o bilateral. Menor estrés en codos que barra.", alternativas:["t1","t5"] },
  { id:"t3", video:"https://www.youtube.com/watch?v=2-LAMcpzODU", nombre:"Extensión en Polea Alta (Pushdown)", grupo:"triceps", equipo:"Cable", tipo:"Aislamiento", dificultad:"Principiante", principal:"Tríceps (cabezas lateral y medial)", secundarios:[], series:"3-4", reps:"12-20", descanso:"60s", rir:"1-2", rpe:"7", notas:"Codos fijos. Excelente tensión constante para el tríceps.", alternativas:["t4","t6"] },
  { id:"t4", video:"https://www.youtube.com/watch?v=kiuVA0gs3EI", nombre:"Extensión en Polea Alta con Cuerda", grupo:"triceps", equipo:"Cable", tipo:"Aislamiento", dificultad:"Principiante", principal:"Tríceps (3 cabezas)", secundarios:[], series:"3-4", reps:"12-20", descanso:"60s", rir:"1-2", rpe:"7", notas:"Separar la cuerda al final para mayor activación.", alternativas:["t3","t6"] },
  { id:"t5", video:"https://www.youtube.com/watch?v=_gsUck-7M74", nombre:"Extensión de Tríceps sobre la Cabeza en Cable", grupo:"triceps", equipo:"Cable", tipo:"Aislamiento", dificultad:"Principiante", principal:"Tríceps (cabeza larga)", secundarios:[], series:"3-4", reps:"12-15", descanso:"60-90s", rir:"2", rpe:"7", notas:"Brazos por encima. Máximo estiramiento de la cabeza larga.", alternativas:["t1","t2"] },
  { id:"t6", video:"https://www.youtube.com/watch?v=6kALZikXxLc", nombre:"Fondos en Banco (Tricep Dips)", grupo:"triceps", equipo:"Peso corporal", tipo:"Compuesto", dificultad:"Principiante", principal:"Tríceps", secundarios:["Deltoides anterior"], series:"3-4", reps:"10-20", descanso:"90s", rir:"2-3", rpe:"7", notas:"Cuerpo vertical, codos pegados al torso.", alternativas:["t3","t7"] },
  { id:"t7", video:"https://www.youtube.com/watch?v=6kALZikXxLc", nombre:"Fondos en Paralelas (Tríceps)", grupo:"triceps", equipo:"Peso corporal", tipo:"Compuesto", dificultad:"Intermedio", principal:"Tríceps", secundarios:["Pectoral","Deltoides"], series:"3-4", reps:"8-15", descanso:"90s", rir:"2-3", rpe:"8", notas:"Torso vertical para enfoque en tríceps.", alternativas:["t6","t3"] },
  { id:"t8", video:"https://www.youtube.com/watch?v=iQ9TT5Wkxpg", nombre:"Kickback con Mancuerna", grupo:"triceps", equipo:"Mancuernas", tipo:"Aislamiento", dificultad:"Principiante", principal:"Tríceps (cabeza lateral)", secundarios:[], series:"3", reps:"12-15", descanso:"60s", rir:"1-2", rpe:"7", notas:"Codo fijo a 90°, extender totalmente.", alternativas:["t3","t4"] },

  // ─── PIERNAS ──────────────────────────────────────────────────────────────
  { id:"l1", video:"https://www.youtube.com/watch?v=ultWZbUMPL8", nombre:"Sentadilla con Barra (Back Squat)", grupo:"piernas", equipo:"Barra libre", tipo:"Compuesto", dificultad:"Avanzado", principal:"Cuádriceps", secundarios:["Glúteos","Isquiotibiales","Core","Aductores"], series:"3-5", reps:"4-10", descanso:"180-300s", rir:"2-3", rpe:"8-9", notas:"El rey de los ejercicios de pierna. Profundidad mínima hasta paralelo. Rodillas alineadas con pies.", alternativas:["l3","l5","l7"] },
  { id:"l2", video:"https://www.youtube.com/watch?v=m4ytaCJZpl0", nombre:"Sentadilla Frontal", grupo:"piernas", equipo:"Barra libre", tipo:"Compuesto", dificultad:"Avanzado", principal:"Cuádriceps", secundarios:["Glúteos","Core"], series:"3-4", reps:"5-10", descanso:"180s", rir:"2-3", rpe:"8", notas:"Mayor activación de cuádriceps que la trasera. Requiere movilidad de tobillo.", alternativas:["l1","l5","l7"] },
  { id:"l3", video:"https://www.youtube.com/watch?v=MeIiIdhvXT4", nombre:"Sentadilla con Mancuernas (Goblet)", grupo:"piernas", equipo:"Mancuernas", tipo:"Compuesto", dificultad:"Principiante", principal:"Cuádriceps", secundarios:["Glúteos","Core"], series:"3-4", reps:"10-15", descanso:"90s", rir:"2-3", rpe:"7", notas:"Ideal para aprender la mecánica de la sentadilla. Peso al pecho.", alternativas:["l1","l5","l7"] },
  { id:"l4", video:"https://www.youtube.com/watch?v=FS-yzDXo4q4", nombre:"Peso Muerto Sumo", grupo:"piernas", equipo:"Barra libre", tipo:"Compuesto", dificultad:"Intermedio", principal:"Aductores", secundarios:["Glúteos","Cuádriceps","Isquiotibiales"], series:"3-5", reps:"5-10", descanso:"180s", rir:"2-3", rpe:"8", notas:"Stance amplio, pies apuntando hacia fuera. Mayor activación de aductores.", alternativas:["e3","e9"] },
  { id:"l5", video:"https://www.youtube.com/watch?v=GvRgijoJ2xY", nombre:"Prensa de Piernas", grupo:"piernas", equipo:"Máquina", tipo:"Compuesto", dificultad:"Principiante", principal:"Cuádriceps", secundarios:["Glúteos","Isquiotibiales"], series:"3-4", reps:"10-15", descanso:"90-120s", rir:"2-3", rpe:"7", notas:"Pies altos = más glúteos. Pies bajos = más cuádriceps.", alternativas:["l1","l3","l7"] },
  { id:"l6", video:"https://www.youtube.com/watch?v=YyvSfVjQeL0", nombre:"Extensión de Cuádriceps en Máquina", grupo:"piernas", equipo:"Máquina", tipo:"Aislamiento", dificultad:"Principiante", principal:"Cuádriceps", secundarios:[], series:"3-4", reps:"12-20", descanso:"60s", rir:"1-2", rpe:"7", notas:"Excelente para aislamiento. Mantener pausa en la contracción.", alternativas:["l7"] },
  { id:"l7", video:"https://www.youtube.com/watch?v=U3HlEF_E9fo", nombre:"Sentadilla Hack con Barra", grupo:"piernas", equipo:"Barra libre", tipo:"Compuesto", dificultad:"Intermedio", principal:"Cuádriceps", secundarios:["Glúteos"], series:"3-4", reps:"8-12", descanso:"120s", rir:"2-3", rpe:"7-8", notas:"Barra detrás. Mayor activación de cuádriceps distales.", alternativas:["l1","l5","l6"] },
  { id:"l8", video:"https://www.youtube.com/watch?v=Orxowest56U", nombre:"Curl de Isquiotibiales Tumbado", grupo:"piernas", equipo:"Máquina", tipo:"Aislamiento", dificultad:"Principiante", principal:"Isquiotibiales", secundarios:[], series:"3-4", reps:"10-15", descanso:"60-90s", rir:"1-2", rpe:"7", notas:"El ejercicio más directo para isquiotibiales.", alternativas:["l9","l10"] },
  { id:"l9", video:"https://www.youtube.com/watch?v=1Tq3QdYUuHs", nombre:"Curl de Isquiotibiales Sentado", grupo:"piernas", equipo:"Máquina", tipo:"Aislamiento", dificultad:"Principiante", principal:"Isquiotibiales", secundarios:[], series:"3-4", reps:"10-15", descanso:"60-90s", rir:"1-2", rpe:"7", notas:"Mayor activación de la cabeza larga del bíceps femoral.", alternativas:["l8","l10"] },
  { id:"l10", video:"https://www.youtube.com/watch?v=d_KZxkY_0cM", nombre:"Nordic Curl (Curl Nórdico)", grupo:"piernas", equipo:"Peso corporal", tipo:"Aislamiento", dificultad:"Avanzado", principal:"Isquiotibiales", secundarios:[], series:"2-4", reps:"3-8", descanso:"120s", rir:"2-3", rpe:"9", notas:"El ejercicio más efectivo para prevenir lesiones de isquiotibiales. Alta dificultad.", alternativas:["l8","l9"] },
  { id:"l11", video:"https://www.youtube.com/watch?v=QOVaHwm-Q6U", nombre:"Zancadas con Barra", grupo:"piernas", equipo:"Barra libre", tipo:"Compuesto", dificultad:"Intermedio", principal:"Cuádriceps", secundarios:["Glúteos","Isquiotibiales"], series:"3-4", reps:"10-15 por pierna", descanso:"90s", rir:"2-3", rpe:"7", notas:"Trabajo unilateral. Excelente para estabilidad y equilibrio.", alternativas:["l12","l13"] },
  { id:"l12", video:"https://www.youtube.com/watch?v=QOVaHwm-Q6U", nombre:"Zancadas con Mancuernas", grupo:"piernas", equipo:"Mancuernas", tipo:"Compuesto", dificultad:"Principiante", principal:"Cuádriceps", secundarios:["Glúteos"], series:"3-4", reps:"12-15 por pierna", descanso:"90s", rir:"2-3", rpe:"7", notas:"Más accesible que con barra. Ideal para principiantes.", alternativas:["l11","l13"] },
  { id:"l13", video:"https://www.youtube.com/watch?v=kkdmHTASZg8", nombre:"Split Squat Búlgaro", grupo:"piernas", equipo:"Mancuernas", tipo:"Compuesto", dificultad:"Intermedio", principal:"Cuádriceps", secundarios:["Glúteos","Isquiotibiales"], series:"3-4", reps:"8-12 por pierna", descanso:"120s", rir:"2-3", rpe:"8", notas:"El mejor ejercicio unilateral de pierna. Pie trasero elevado.", alternativas:["l11","l12"] },
  { id:"l14", video:"https://www.youtube.com/watch?v=OKn_6Me96-Y", nombre:"Elevación de Pantorrillas de Pie", grupo:"piernas", equipo:"Máquina", tipo:"Aislamiento", dificultad:"Principiante", principal:"Gastrocnemio", secundarios:["Sóleo"], series:"3-5", reps:"10-20", descanso:"60s", rir:"1-2", rpe:"7", notas:"Rodillas extendidas para activar el gastrocnemio.", alternativas:["l15"] },
  { id:"l15", video:"https://www.youtube.com/watch?v=JOh-XTXRTOU", nombre:"Elevación de Pantorrillas Sentado", grupo:"piernas", equipo:"Máquina", tipo:"Aislamiento", dificultad:"Principiante", principal:"Sóleo", secundarios:["Gastrocnemio"], series:"3-4", reps:"12-20", descanso:"60s", rir:"1-2", rpe:"7", notas:"Rodillas flexionadas a 90°. Activa más el sóleo.", alternativas:["l14"] },

  // ─── GLÚTEOS ──────────────────────────────────────────────────────────────
  { id:"g1", video:"https://www.youtube.com/watch?v=SEdqd1n0cvg", nombre:"Hip Thrust con Barra", grupo:"gluteos", equipo:"Barra libre", tipo:"Compuesto", dificultad:"Principiante", principal:"Glúteo mayor", secundarios:["Isquiotibiales","Cuádriceps"], series:"3-5", reps:"8-15", descanso:"90-120s", rir:"1-2", rpe:"8", notas:"El ejercicio más efectivo para el glúteo mayor. Espalda sobre banco, barra en cadera.", alternativas:["g2","g3","g4"] },
  { id:"g2", video:"https://www.youtube.com/watch?v=SEdqd1n0cvg", nombre:"Hip Thrust con Mancuerna", grupo:"gluteos", equipo:"Mancuernas", tipo:"Compuesto", dificultad:"Principiante", principal:"Glúteo mayor", secundarios:["Isquiotibiales"], series:"3-4", reps:"12-20", descanso:"90s", rir:"1-2", rpe:"7", notas:"Versión más accesible. Mancuerna en el pliegue de la cadera.", alternativas:["g1","g3","g4"] },
  { id:"g3", video:"https://www.youtube.com/watch?v=OUgsJ8-Vi0E", nombre:"Puente de Glúteos", grupo:"gluteos", equipo:"Peso corporal", tipo:"Compuesto", dificultad:"Principiante", principal:"Glúteo mayor", secundarios:["Isquiotibiales","Core"], series:"3-4", reps:"15-20", descanso:"60s", rir:"1-2", rpe:"6", notas:"Versión básica del hip thrust. Ideal para activación.", alternativas:["g1","g2"] },
  { id:"g4", video:"https://www.youtube.com/watch?v=aclHkVaku9U", nombre:"Sentadilla Sumo con Mancuerna", grupo:"gluteos", equipo:"Mancuernas", tipo:"Compuesto", dificultad:"Principiante", principal:"Glúteo mayor y medio", secundarios:["Aductores","Cuádriceps"], series:"3-4", reps:"12-15", descanso:"90s", rir:"2-3", rpe:"7", notas:"Stance ancho, pies 45°. Mayor activación de glúteo medio.", alternativas:["l1","l5"] },
  { id:"g5", video:"https://www.youtube.com/watch?v=Ev8IAqWAkEk", nombre:"Patada de Glúteo en Cable", grupo:"gluteos", equipo:"Cable", tipo:"Aislamiento", dificultad:"Principiante", principal:"Glúteo mayor", secundarios:[], series:"3-4", reps:"15-20 por pierna", descanso:"60s", rir:"1-2", rpe:"6", notas:"Extensión de cadera pura. Cable en tobillo.", alternativas:["g6","g7"] },
  { id:"g6", video:"https://www.youtube.com/watch?v=sznANKPzR_s", nombre:"Abducción de Cadera en Máquina", grupo:"gluteos", equipo:"Máquina", tipo:"Aislamiento", dificultad:"Principiante", principal:"Glúteo medio y menor", secundarios:["TFL"], series:"3-4", reps:"15-20", descanso:"60s", rir:"1-2", rpe:"6", notas:"Fundamental para el glúteo medio. Estabilizador de la cadera.", alternativas:["g7"] },
  { id:"g7", video:"https://www.youtube.com/watch?v=sznANKPzR_s", nombre:"Abducción de Cadera con Banda Elástica", grupo:"gluteos", equipo:"Peso corporal", tipo:"Aislamiento", dificultad:"Principiante", principal:"Glúteo medio", secundarios:["Glúteo menor"], series:"3-4", reps:"15-25", descanso:"60s", rir:"1-2", rpe:"6", notas:"Banda en rodillas. Excelente para activación.", alternativas:["g6"] },
  { id:"g8", video:"https://www.youtube.com/watch?v=dQqApCGd5Ss", nombre:"Step Up con Mancuernas", grupo:"gluteos", equipo:"Mancuernas", tipo:"Compuesto", dificultad:"Principiante", principal:"Glúteo mayor", secundarios:["Cuádriceps","Isquiotibiales"], series:"3-4", reps:"10-15 por pierna", descanso:"90s", rir:"2-3", rpe:"7", notas:"Cajón a altura de rodilla. Impulso desde el talón.", alternativas:["g1","l13"] },

  // ─── CORE ─────────────────────────────────────────────────────────────────
  { id:"c1", video:"https://www.youtube.com/watch?v=pSHjTRCQxIw", nombre:"Plancha Frontal", grupo:"core", equipo:"Peso corporal", tipo:"Isométrico", dificultad:"Principiante", principal:"Transverso abdominal", secundarios:["Recto abdominal","Oblicuos","Glúteos"], series:"3-4", reps:"30-90s", descanso:"60s", rir:"N/A", rpe:"7", notas:"Cuerpo recto. Glúteos activados. Sin arquear la espalda.", alternativas:["c2","c5"] },
  { id:"c2", video:"https://www.youtube.com/watch?v=_rdfjFSFKsY", nombre:"Plancha Lateral", grupo:"core", equipo:"Peso corporal", tipo:"Isométrico", dificultad:"Principiante", principal:"Oblicuos", secundarios:["Transverso abdominal","Glúteo medio"], series:"3-4", reps:"20-60s por lado", descanso:"60s", rir:"N/A", rpe:"7", notas:"Cuerpo alineado lateralmente. Cadera elevada.", alternativas:["c1","c6"] },
  { id:"c3", video:"https://www.youtube.com/watch?v=Xyd_fa5zoEU", nombre:"Crunch Abdominal", grupo:"core", equipo:"Peso corporal", tipo:"Dinámico", dificultad:"Principiante", principal:"Recto abdominal (porción superior)", secundarios:["Oblicuos"], series:"3-4", reps:"15-25", descanso:"60s", rir:"1-2", rpe:"7", notas:"Flexión de columna, no de cadera. Manos en sien.", alternativas:["c4","c7"] },
  { id:"c4", video:"https://www.youtube.com/watch?v=ub5GxzEhP4E", nombre:"Crunch en Máquina / Cable", grupo:"core", equipo:"Cable", tipo:"Dinámico", dificultad:"Principiante", principal:"Recto abdominal", secundarios:["Oblicuos"], series:"3-4", reps:"15-25", descanso:"60s", rir:"1-2", rpe:"7", notas:"Sobrecarga progresiva posible. Más efectivo que crunch libre.", alternativas:["c3","c7"] },
  { id:"c5", video:"https://www.youtube.com/watch?v=A8JmFBb4n9Q", nombre:"Ab Wheel (Rueda Abdominal)", grupo:"core", equipo:"Peso corporal", tipo:"Dinámico", dificultad:"Avanzado", principal:"Recto abdominal", secundarios:["Transverso","Oblicuos","Dorsales"], series:"3-4", reps:"8-15", descanso:"90s", rir:"2-3", rpe:"8-9", notas:"Uno de los ejercicios más completos de core. Extensión controlada.", alternativas:["c1","c3"] },
  { id:"c6", video:"https://www.youtube.com/watch?v=wkD8rjkodUI", nombre:"Russian Twist", grupo:"core", equipo:"Peso corporal", tipo:"Dinámico", dificultad:"Principiante", principal:"Oblicuos", secundarios:["Recto abdominal"], series:"3-4", reps:"15-20 por lado", descanso:"60s", rir:"1-2", rpe:"7", notas:"Rotación de torso. Agregar peso para mayor intensidad.", alternativas:["c2","c8"] },
  { id:"c7", video:"https://www.youtube.com/watch?v=JB2oyawG9KI", nombre:"Elevación de Piernas Colgado", grupo:"core", equipo:"Barra fija", tipo:"Dinámico", dificultad:"Intermedio", principal:"Recto abdominal (porción inferior)", secundarios:["Flexores de cadera","Oblicuos"], series:"3-4", reps:"10-15", descanso:"60-90s", rir:"2-3", rpe:"7-8", notas:"No usar impulso. Control total en la bajada.", alternativas:["c3","c4"] },
  { id:"c8", video:"https://www.youtube.com/watch?v=AH_QZLm_0-s", nombre:"Pallof Press", grupo:"core", equipo:"Cable", tipo:"Isométrico", dificultad:"Principiante", principal:"Oblicuos (anti-rotación)", secundarios:["Transverso abdominal"], series:"3-4", reps:"10-12 por lado", descanso:"60s", rir:"2", rpe:"6-7", notas:"Core anti-rotacional. Fundamental para estabilidad funcional.", alternativas:["c2","c6"] },
  { id:"c9", video:"https://www.youtube.com/watch?v=4XLEnwUr1d8", nombre:"Dead Bug", grupo:"core", equipo:"Peso corporal", tipo:"Dinámico", dificultad:"Principiante", principal:"Transverso abdominal", secundarios:["Oblicuos","Recto abdominal"], series:"3", reps:"8-12 por lado", descanso:"60s", rir:"2", rpe:"6", notas:"Estabilización lumbar. Espalda completamente pegada al suelo.", alternativas:["c1","c5"] },

  // ─── CARDIO ───────────────────────────────────────────────────────────────
  { id:"cv1", video:"https://www.youtube.com/watch?v=ml6cT4AZdqI", nombre:"HIIT en Bicicleta Estática", grupo:"cardio", equipo:"Máquina", tipo:"Cardiovascular", dificultad:"Intermedio", principal:"Sistema cardiovascular", secundarios:["Cuádriceps","Glúteos"], series:"8-12", reps:"20s ON / 40s OFF", descanso:"Incluido", rir:"N/A", rpe:"8-9 en intervalos", notas:"Protocolo Tabata o similar. Superior a cardio continuo para quema de grasa y VO2max.", alternativas:["cv2","cv3"] },
  { id:"cv2", video:"https://www.youtube.com/watch?v=iN-FnfxoC3Y", nombre:"HIIT en Cinta de Correr", grupo:"cardio", equipo:"Máquina", tipo:"Cardiovascular", dificultad:"Intermedio", principal:"Sistema cardiovascular", secundarios:["Cuádriceps","Glúteos","Isquiotibiales"], series:"8-10", reps:"30s sprint / 90s trote", descanso:"Incluido", rir:"N/A", rpe:"8-9 en sprints", notas:"Sprints al 90% + recuperación activa. Muy efectivo para pérdida de grasa.", alternativas:["cv1","cv4"] },
  { id:"cv3", video:"https://www.youtube.com/watch?v=JSUIQgY9oHg", nombre:"Cardio Continuo en Bicicleta", grupo:"cardio", equipo:"Máquina", tipo:"Cardiovascular", dificultad:"Principiante", principal:"Sistema cardiovascular", secundarios:["Cuádriceps"], series:"1", reps:"20-60 min", descanso:"N/A", rir:"N/A", rpe:"5-7", notas:"Zona 2 (60-70% FC máx). Excelente para base aeróbica y recuperación activa.", alternativas:["cv4","cv5"] },
  { id:"cv4", video:"https://www.youtube.com/watch?v=iN-FnfxoC3Y", nombre:"Cardio Continuo en Cinta", grupo:"cardio", equipo:"Máquina", tipo:"Cardiovascular", dificultad:"Principiante", principal:"Sistema cardiovascular", secundarios:["Cuádriceps","Glúteos","Core"], series:"1", reps:"20-60 min", descanso:"N/A", rir:"N/A", rpe:"5-7", notas:"Trote moderado zona 2. Mayor impacto articular que bicicleta.", alternativas:["cv3","cv5"] },
  { id:"cv5", video:"https://www.youtube.com/watch?v=IekFHRuXubc", nombre:"Remo Ergómetro", grupo:"cardio", equipo:"Máquina", tipo:"Cardiovascular", dificultad:"Intermedio", principal:"Sistema cardiovascular", secundarios:["Espalda","Piernas","Core","Brazos"], series:"1 o intervalos", reps:"15-30 min", descanso:"N/A", rir:"N/A", rpe:"6-8", notas:"El cardio más completo. Activa el 86% de los músculos del cuerpo.", alternativas:["cv1","cv3"] },
  { id:"cv6", video:"https://www.youtube.com/watch?v=u3zgHI8QnqE", nombre:"Cuerda para Saltar (Jump Rope)", grupo:"cardio", equipo:"Peso corporal", tipo:"Cardiovascular", dificultad:"Principiante", principal:"Sistema cardiovascular", secundarios:["Pantorrillas","Coordinación"], series:"Intervalos", reps:"30-60s ON / 30s OFF", descanso:"Incluido", rir:"N/A", rpe:"7-8", notas:"Excelente coordinación y cardio. Bajo costo, alta efectividad.", alternativas:["cv2","cv7"] },
  { id:"cv7", video:"https://www.youtube.com/watch?v=muF-knm3HCc", nombre:"Battle Ropes (Cuerdas de Batalla)", grupo:"cardio", equipo:"Peso corporal", tipo:"Cardiovascular", dificultad:"Intermedio", principal:"Sistema cardiovascular", secundarios:["Hombros","Core","Brazos"], series:"5-10", reps:"20-30s ON / 30-40s OFF", descanso:"Incluido", rir:"N/A", rpe:"8-9", notas:"Cardio de alta intensidad con componente de fuerza.", alternativas:["cv1","cv6"] },
  { id:"cv8", video:"https://www.youtube.com/watch?v=7oGOKQkFmVQ", nombre:"Escaladora (StairMaster)", grupo:"cardio", equipo:"Máquina", tipo:"Cardiovascular", dificultad:"Principiante", principal:"Sistema cardiovascular", secundarios:["Glúteos","Cuádriceps","Pantorrillas"], series:"1", reps:"15-45 min", descanso:"N/A", rir:"N/A", rpe:"6-8", notas:"Bajo impacto, alta quema calórica. Excelente para glúteos y cardiovascular.", alternativas:["cv3","cv4"] },
];

export const METODOS_INTENSIDAD = {
  estandar: { nombre:"Series estándar", descripcion:"Mismo peso y reps en todas las series", icono:"📊" },
  piramide_asc: { nombre:"Pirámide ascendente", descripcion:"↑ peso, ↓ reps por serie", icono:"📈", ejemplo:"60kg×15 → 70kg×12 → 80kg×8 → 90kg×5" },
  piramide_desc: { nombre:"Pirámide descendente", descripcion:"↓ peso, ↑ reps por serie", icono:"📉", ejemplo:"90kg×5 → 80kg×8 → 70kg×12 → 60kg×15" },
  piramide_doble: { nombre:"Pirámide doble", descripcion:"Sube y vuelve a bajar el peso", icono:"💎", ejemplo:"60→70→80→70→60 kg" },
  rest_pause: { nombre:"Rest-Pause", descripcion:"Pausa 10-15s dentro de la serie para continuar", icono:"⏸️", ejemplo:"12 reps → 15s pausa → 6 reps → 15s pausa → 4 reps" },
  drop_set: { nombre:"Drop Set", descripcion:"Reducir 20-30% el peso al fallo sin descanso", icono:"⬇️", ejemplo:"80kg×10 fallo → 60kg×8 fallo → 50kg×8 fallo" },
  superset: { nombre:"Superset", descripcion:"2 ejercicios sin descanso entre ellos", icono:"🔄", ejemplo:"Press banca + Dominadas → Descanso 90s → Repetir" },
  triset: { nombre:"Triset", descripcion:"3 ejercicios sin descanso", icono:"🔁", ejemplo:"Curl + Martillo + Inverso → Descanso 120s" },
  giant_set: { nombre:"Giant Set", descripcion:"4+ ejercicios sin descanso", icono:"💥", ejemplo:"4-6 ejercicios consecutivos para un grupo muscular" },
  pre_fatiga: { nombre:"Pre-fatiga", descripcion:"Aislamiento antes del compuesto", icono:"🎯", ejemplo:"Pec Deck → inmediatamente Press Banca" },
  post_fatiga: { nombre:"Post-fatiga", descripcion:"Aislamiento después del compuesto", icono:"🎯", ejemplo:"Press Banca → inmediatamente Aperturas" },
  tempo: { nombre:"Tempo Training", descripcion:"Control de tiempo en cada fase (exc/pausa/con)", icono:"⏱️", ejemplo:"4-1-2-0: 4s bajar, 1s pausa, 2s subir, 0s arriba" },
  cluster: { nombre:"Cluster Sets", descripcion:"Mini-descansos de 10-20s dentro de la serie", icono:"🧩", ejemplo:"5 reps → 15s → 5 reps → 15s → 5 reps (total 15 reps)" },
};
